[
    {
        sku: 'M034',
        title:'Pies Descalzos',
        artist: 'Shakira',
        genre: 'Pop',
        release_year: 2000,
        format: 'CD',
        price: 50000,
        stock: 6,
        rating: 4.2,
        tags: ['clásico', 'coleccionable', 'edición especial'],
        label: {
                name: 'Atlantic Music',
                country: 'Colombia'}
        },
    {
        sku: 'M018',
        title:'Borró Cassette',
        artist: 'Maluma',
        genre: 'Reggueton',
        release_year: 2010,
        format: 'CD',
        price: 2000,
        stock: 12,
        rating: 2.9,
        tags: ['Bailable'],
        label: {
                name: 'Hear This Music',
                country: 'Ecuador'}
        },
    {
        sku: 'M059',
        title:'DTMF',
        artist: 'Bad Bunny',
        genre: 'Pop',
        release_year: 2000,
        format: 'CD',
        price: 120000,
        stock: 0,
        rating: 3.8,
        tags: ['Bailable', 'Perreo'],
        label: {
                name: 'Atlantic Records',
                country: 'Estados Unidos'}
        },
    
    {
        sku: 'M012',
        title:'La Copa Rota',
        artist: 'Alci Acosta',
        genre: 'Balada',
        release_year: 1980,
        format: 'Vinilo',
        price: 200000,
        stock: 2,
        rating: 4.9,
        tags: ['clásico', 'coleccionable', 'edición especial'],
        label: {
                name: 'Hear This Music',
                country: 'Venezuela'}
        },
    
    {
        sku: 'M033',
        title:'Thriller',
        artist: 'Maikol Jackson',
        genre: 'Rock',
        release_year: 1600,
        format: 'Vinilo',
        price: 30000,
        stock: 5,
        rating: 4.8,
        tags: ['Popular', 'coleccionable', 'edición especial'],
        label: {
                name: 'Sonyc Music',
                country: 'Perú'}
        },
    
    {
        sku: 'M025',
        title:'El cóndor Herido',
        artist: 'Diomedes Diaz',
        genre: 'Vallenato',
        release_year: 2025,
        format: 'Vinilo',
        price: 60000,
        stock: 0,
        rating: 4.8,
        tags: ['oferta', 'coleccionable'],
        label: {
                name: 'Sonyc Records',
                country: 'Canadá'}
        },
    
    {
        sku: 'M043',
        title:'Esa Mujer',
        artist: 'Silvestre Dangon',
        genre: 'Vallenato',
        release_year: 1999,
        format: 'CD',
        price: 2000,
        stock: 5,
        rating: 2.8,
        tags: ['Oferta', 'Popular', 'Colecionable'],
        label: {
                name: 'Hear This Music',
                country: 'Colombia'}
        },
    
    {
        sku: 'M066',
        title:'Óyete esta',
        artist: 'Manuel Medrano',
        genre: 'Trap',
        release_year: 20524,
        format: 'CD',
        price: 55000,
        stock: 2,
        rating: 2.6,
        tags: ['Oferta', 'Popular'],
        label: {
                name: 'Atlantic Records',
                country: 'Colombia'}
        },
    
    {
        sku: 'M067',
        title:'Mátalas',
        artist: 'Vicente Fernández',
        genre: 'De Cantina',
        release_year: 1300,
        format: 'Vinilo',
        price: 30000,
        stock: 0,
        rating: 5.0,
        tags: ['Popular', 'edición especial'],
        label: {
                name: 'Sonyc Records',
                country: 'Mexico'}
        },
    
    {
        sku: 'M068',
        title:'0 sentimientos',
        artist: 'Julio Jaramillo',
        genre: 'Trap',
        release_year: 2023,
        format: 'CD',
        price: 20000,
        stock: 1,
        rating: 4.6,
        tags: ['clásico', 'Popular', 'edición especial'],
        label: {
                name: 'Hear This Music',
                country: 'Estados Unidos'}
        },
    
    {
        sku: 'M069',
        title:'La mujer que bota fuego',
        artist: 'Manuel Turizo',
        genre: 'Rock',
        release_year: 2022,
        format: 'Vinilo',
        price: 65000,
        stock: 2,
        rating: 4.9,
        tags: ['Oferta', 'nuevo', 'edición especial'],
        label: {
                name: 'Atlantic Records',
                country: 'Colombia'}
        },
    
    ]